#!/bin/bash

set -e

COMMIT=$1

shift 1

echo "Initializing Backport Process for Commit $COMMIT"

TARGETS=$*
echo "Targets: $TARGETS"

CUR_BRANCH="$(git symbolic-ref HEAD 2>/dev/null)" ||
CUR_BRANCH="(unnamed branch)"     # detached HEAD
CUR_BRANCH=${CUR_BRANCH##refs/heads/}

for BRANCH in $TARGETS
do
    git checkout $BRANCH
    git pull
    git cherry-pick $COMMIT
    git push
done

if [ "$CUR_BRANCH" != "(unnamed branch)" ]
then
    git checkout $CUR_BRANCH
fi
echo "Done"